### ISSUE TITLE
Add public var to access current sessionID

### ISSUE THREAD

**Issue by robcreatively** [segment-integrations/analytics-swift-amplitude#11]
In order to keep analytics events sent from the client and backend as part of the same Amplitude session we need to be able to pass the current sessionID to the server. There does not appear to be an easy way to access the current sessionID.

**Comment by bsneed** [comment]
You should fork the repo and modify as necessary.  Keeping a desired sessionID current with how amplitude needs it reset and when it needs reset will likely be brittle.
