### ISSUE TITLE
question about migrating from old plugin to this plugin

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-swift-amplitude#13]
In the [older variant of this plugin](https://github.com/segment-integrations/analytics-ios-integration-amplitude.git), there was code that would do revenue tracking. 
It would look at the properties being sent to segment, and see if there was one named "revenue" or "total", and then also look at things like "price" and "quantity". 
This new plugin doesn't do much client-side, I'm assuming because we expect this to be done in the cloud. Is this what the "Log Purchase" action is, in the "Amplitude (Actions) Destination" ?

I really wish there were a good migration document about this.

**Comment by bsneed** [comment]
Yeah, all the stuff the old one did is now done in the cloud and without the Amplitude SDK.  I hear you re documentation, it's hard to be an expert in all these various destinations.  Reaching out to Segment's support team is a great way to get it on someones radar.  I think the expectation was "it would just work" so not much was needed in docs.  Feel free to reopen this if you need further help or clarification.
