### ISSUE TITLE
Session Start and Session End events are not sent

### ISSUE THREAD

**Issue by remstos** [segment-integrations/analytics-swift-amplitude#16]
Using the AmplitudeSession plugin correctly updates the session_id for events but session events are not sent

Exemple running the app, going to background and resuming the app after more than 5 min:

### Result

The last Application Foregrounded correctly has a new session id, but no session events where triggered.

<img width="524" alt="Screenshot 2024-02-14 at 13 30 37" src="https://github.com/segment-integrations/analytics-swift-amplitude/assets/4311124/af345090-f375-4b0c-b8f6-cf8173709e6f">

The Amplitude iOS SDK seems to have a slightly different implentation for the session handling : https://github.com/amplitude/Amplitude-Swift/blob/main/Sources/Amplitude/Sessions.swift
It could be confusing that the plugin here doesn’t produce the same behaviors.

Current workaround is to still install the Amplitude iOS SDK and setup only session events. But that’s not ideal Segment usage, especially since it’s already close to perfect.

Thanks 🙏

**Comment by alanjcharles** [comment]
Hi @remstos thanks for reaching out- I'll take a look this week

**Comment by bsneed** [comment]
Hi @remstos, please check out release 1.4.0.  It should cover all but the "screen" issue.

**Comment by ivan-r** [comment]
Hey @bsneed, there's a crash on 1.4.0, created an issue about it.

**Comment by bsneed** [comment]
Thanks @ivan-r; I was just able to reproduce it by clearing the sessionID.  I'm gonna pull 1.4.0 down for now.

**Comment by bsneed** [comment]
Ok, screen is working now and the recursion issue with 1.4.0 is fixed in 1.4.1.

**Comment by remstos** [comment]
Hi @alanjcharles & @bsneed 

I’ve updated to 1.4.1 and stopped using our fork. This seems to be working correctly now.
Thanks a lot for this update 🙏

**Comment by alanjcharles** [comment]
no problem @remstos! thank you for letting us know
