### ISSUE TITLE
Application lifecycle event don’t appear in Amplitude

### ISSUE THREAD

**Issue by remstos** [segment-integrations/analytics-swift-amplitude#25]
Hi,

Ever since [this change](https://github.com/segment-integrations/analytics-swift-amplitude/pull/21) about session events. (thanks for the reactivity on that issue)

The Amplitude destination doesn’t receive anymore the events. Meaning they don’t appear in Amplitude at all

#### Events receiving in Segment

<img width="858" alt="Screenshot 2024-06-20 at 10 50 23" src="https://github.com/segment-integrations/analytics-swift-amplitude/assets/4311124/d07d7755-d0d9-4b94-acde-b988b41c802b">

#### Only session events appearing in Amplitude

<img width="852" alt="Screenshot 2024-06-20 at 10 50 51" src="https://github.com/segment-integrations/analytics-swift-amplitude/assets/4311124/ab6f8366-0a8d-4471-9245-57d8951d33bc">

#### Workaround

For now I can fork and comment out `AmplitudeSession.swift` Line:151 to Line:169

<img width="399" alt="Screenshot 2024-06-20 at 10 57 37" src="https://github.com/segment-integrations/analytics-swift-amplitude/assets/4311124/d758af67-c507-400e-bd65-563be3d05350">

Thanks

**Comment by bsneed** [comment]
We made an update and reverted previous changes.  Please reach out to friends@segment.com for assistance.
