### ISSUE TITLE
Session ID is -1 despite adding AmplitudeSession plugin

### ISSUE THREAD

**Issue by amyacuff** [segment-integrations/analytics-swift-amplitude#8]
Using Swift Packages:
Segment 1.4.6
SegmentAmplitude 1.2.0

Setup:
`let config = Configuration(writeKey: segmentApiKey)
            .trackApplicationLifecycleEvents(true)

        let segment = Analytics(configuration: config)
        segment.add(plugin: AmplitudeSession())`

Calling segment.track(name: "example") on an authenticated user results in the event showing up in Amplitude but the Session ID is always -1.  I am using cloud mode for Segment -> Amplitude.

**Comment by TheNorthEestern** [comment]
Also experiencing this

**Comment by alanjcharles** [comment]
Hi @amyacuff @TheNorthEestern apologies for the long delay here. Are you still experiencing this issue? When I build and send and event to Amplitude I am getting the `sessionId` 

![image](https://github.com/segment-integrations/analytics-swift-amplitude/assets/50601149/6e9b3d4b-a26e-49d4-93bc-12763e0f72bd)

I'm going to close but please feel free to re-open with any additional information or reach out to `friends@segment.com` for a more thorough investigation. They can escalate issues to us accordingly. Thanks!

**Comment by lluisgerard** [comment]
I also have this issue...
When I look at the Debugger all events come with integrations empty like so `"integrations": {}`.

_Segment 1.5.2
SegmentAmplitude 1.3.0_

**Comment by lluisgerard** [comment]
I've been messing around with an instance of `AmplitudeSession()`.

I found this function that always sets active `false` because the key "Actions Amplitude" is never found:

```
    public func update(settings: Settings, type: UpdateType) {
        if settings.hasIntegrationSettings(key: key) {
            active = true
        } else {
            active = false
        }
    }
```

This is the key property I'm referring to:
```
public class AmplitudeSession: EventPlugin, iOSLifecycle {
    public var key = "Actions Amplitude"
```

For testing purposes I tweaked the key property like so:

```
let amplitudePlugin = AmplitudeSession()
        amplitudePlugin.key = "Segment.io"
        analytics = Segment.Analytics(configuration: Segment.Configuration(writeKey: self.key)
            .flushAt(3)
            .trackApplicationLifecycleEvents(true))
        analytics.add(plugin: SegmentIDFACollection())
        analytics.add(plugin: amplitudePlugin)
```

When doing this I finally get the integration on the debugger but I wonder if this is going to work on production (I don't have amplitude on dev to test this but I can send a build to TestFlight and check). Any way, this is the debugger:
```
  "integrations": {
    "Segment.io": {
      "session_id": 1707498874000
    }
  },
```

I know this is a hacky way to get the SDK to add the integration but I believe the issue is in that key or in `Settings.integrations`... 

I hope this can help you in some way @alanjcharles sorry if it's a bit messy but I'm not familiar with the implementation.

**Comment by bsneed** [comment]
@lluisgerard you need to have an Amplitude (Actions) destination set up on your segment source (at app.segment.com).  It sounds like this piece probably hasn't happened yet.

**Comment by lluisgerard** [comment]
@bsneed Thanks for the reply. 

We've been using Segment and Amplitude for years with web, Android, and iOS. We have all the destinations on production. We do get events from iOS on Amplitude but they don't have any session_id (-1).

<img width="1229" alt="image" src="https://github.com/segment-integrations/analytics-swift-amplitude/assets/1152968/92eb62e1-a8ce-4854-aeb1-13ac3dd9291a">

Production Debugger also shows `"integrations": {}`

You are right that I don't have a destination on our development environment (where I was testing this). But it is on production, running the same code, and we do get events from iOS, but these events have no session_id.

**Comment by alanjcharles** [comment]
Hi @lluisgerard just to clarify- there is a difference between the Amplitude (Classic) device-mode destination and the Amplitude (Actions) destination.  I have included a screenshot that shows where you choose between the two when adding a new Amplitude Destination to a given source:
<img width="816" alt="image" src="https://github.com/segment-integrations/analytics-swift-amplitude/assets/50601149/cffd57ae-726c-4181-9f46-fd19ed2985c7">

It is also outlined here in the [Analytics Swift Amplitude Plugin](https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/destination-plugins/amplitude-swift/)  `Getting Started` documentation. 

We created `Action Destinations` to make it possible to use historically popular device-mode destinations via a cloud-mode connection (ie you don't need to include Amplitude's SDK anymore to collect session data). 

Can you just confirm you have the correct destination set up in your Amplitude workspace?  Thanks!

**Comment by lluisgerard** [comment]
Thank you very much for your help @alanjcharles I'm going to check this with the person in charge of the destinations, we are indeed using a "Classic" one here. I didn't realize there are two different frameworks as the events did come through, it's just session_id that was missing. Thank you again.

**Comment by alanjcharles** [comment]
No problem at all! Apologies for the confusion. Please just let me know if anything else comes up!
